Changes to compile and run local_GUI/start.py
This has a few import errors still, see:

Traceback (most recent call last):
File "start.py", line 17, in <module>
ImportError: No module named main_ICS

However, it is much closer to correct. Also, a specific Visual studio
C++ redistributable is
required for pyQT, and has been included. This makes it pretty certain I
should make an
installer.